Repository SDWebImage/SDWebImage, pull requests merged in 2018-03, with the labels that each got.

#2244 Clarify the block comment in SDWebImageManager
  SDWebImage/SDWebImageManager.m
Labels: documents

#2246 Add a delegate method to control the custom logic when blocking the failed url
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageManager.m
Labels: feature

#2191 Refactor the implementation of SDWebImagePrefetcher
  SDWebImage/SDWebImagePrefetcher.h
  SDWebImage/SDWebImagePrefetcher.m
  Tests/Tests/SDWebImagePrefetcherTests.m
Labels: refactoring

#2250 Refactor api style
  Examples/SDWebImage OSX Demo/ViewController.m
  SDWebImage/SDImageCache.h
  SDWebImage/SDImageCache.m
  SDWebImage/SDWebImageCodersManager.h
  SDWebImage/SDWebImageCodersManager.m
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloader.m
  SDWebImage/SDWebImageDownloaderOperation.m
  SDWebImage/SDWebImageGIFCoder.h
  SDWebImage/SDWebImageImageIOCoder.h
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImagePrefetcher.h
  SDWebImage/SDWebImageWebPCoder.h
  SDWebImage/UIImage+ForceDecode.m
  SDWebImage/UIImage+MultiFormat.m
  Tests/Tests/SDImageCacheTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
Labels: refactoring

#2245 Add cacheKeyFilter to allow user provide modified version of data when storing the disk cache in SDWebImageManager
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageManager.m
Labels: feature

#2219 Feature image transformer
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/SDImageCache.h
  SDWebImage/SDImageCache.m
  SDWebImage/SDWebImageCompat.h
  SDWebImage/SDWebImageDefine.h
  SDWebImage/SDWebImageDefine.m
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageManager.m
  SDWebImage/SDWebImageTransformer.h
  SDWebImage/SDWebImageTransformer.m
  SDWebImage/UIImage+Transform.h
  SDWebImage/UIImage+Transform.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/SDWebImageManagerTests.m
  Tests/Tests/SDWebImageTestTransformer.h
  Tests/Tests/SDWebImageTestTransformer.m
  Tests/Tests/SDWebImageTransformerTests.m
  WebImage/SDWebImage.h
Labels: feature, refactoring

#2260 Fix the wrong declaration of NSArray generics
  SDWebImage/SDWebImageCodersManager.h
  SDWebImage/SDWebImageCodersManager.m
Labels: fix

#2140 Introduce SDAnimatedImageView, SDAnimatedImage and do refactory
  Examples/SDWebImage Demo/DetailViewController.m
  Examples/SDWebImage Demo/MasterViewController.m
  Examples/SDWebImage Demo/en.lproj/DetailViewController.xib
  Examples/SDWebImage OSX Demo/Base.lproj/Main.storyboard
  Examples/SDWebImage OSX Demo/ViewController.m
  Examples/SDWebImage TV Demo/Base.lproj/Main.storyboard
  Examples/SDWebImage TV Demo/ViewController.m
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/NSImage+Additions.h
  SDWebImage/NSImage+Additions.m
  SDWebImage/SDAnimatedImage.h
  SDWebImage/SDAnimatedImage.m
  SDWebImage/SDAnimatedImageView+WebCache.h
  SDWebImage/SDAnimatedImageView+WebCache.m
  SDWebImage/SDAnimatedImageView.h
  SDWebImage/SDAnimatedImageView.m
  SDWebImage/SDImageCache.h
  SDWebImage/SDImageCache.m
  SDWebImage/SDWebImageCoder.h
  SDWebImage/SDWebImageCoder.m
  SDWebImage/SDWebImageCoderHelper.h
  SDWebImage/SDWebImageCoderHelper.m
  SDWebImage/SDWebImageCodersManager.m
  SDWebImage/SDWebImageCompat.h
  SDWebImage/SDWebImageCompat.m
  SDWebImage/SDWebImageDefine.h
  SDWebImage/SDWebImageDefine.m
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloaderOperation.m
  SDWebImage/SDWebImageGIFCoder.h
  SDWebImage/SDWebImageGIFCoder.m
  SDWebImage/SDWebImageImageIOCoder.m
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageManager.m
  SDWebImage/SDWebImageWebPCoder.h
  SDWebImage/SDWebImageWebPCoder.m
  SDWebImage/UIImage+ForceDecode.m
  SDWebImage/UIImage+GIF.h
  SDWebImage/UIImage+GIF.m
  SDWebImage/UIImage+MultiFormat.h
  SDWebImage/UIImage+MultiFormat.m
  SDWebImage/UIImage+Transform.m
  SDWebImage/UIImage+WebCache.h
  SDWebImage/UIImage+WebCache.m
  SDWebImage/UIImage+WebP.h
  SDWebImage/UIImage+WebP.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/SDAnimatedImageTest.m
  Tests/Tests/SDTestCase.h
  Tests/Tests/SDTestCase.m
  Tests/Tests/SDWebImageDecoderTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImageTestDecoder.h
  Tests/Tests/SDWebImageTestDecoder.m
  WebImage/SDWebImage.h
Labels: feature

#2149 Add APNG coder support
  Examples/SDWebImage Demo/MasterViewController.m
  Examples/SDWebImage OSX Demo/ViewController.m
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/SDAnimatedImageRep.h
  SDWebImage/SDAnimatedImageRep.m
  SDWebImage/SDWebImageAPNGCoder.h
  SDWebImage/SDWebImageAPNGCoder.m
  SDWebImage/SDWebImageCodersManager.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/Images/TestImageAnimated.apng
  Tests/Tests/SDWebImageDecoderTests.m
  WebImage/SDWebImage.h
Labels: feature
