Repository SDWebImage/SDWebImage, pull requests merged in 2018-05, with the labels that each got.

#2313 Remove the extra calculation of image orientation for ImageIO coder
  SDWebImage/SDWebImageImageIOCoder.m
  Tests/Tests/SDWebImageDecoderTests.m
Labels: performance

#2314 Remove the duplicated process to force decode (draw on bitmap context) in Image/IO's progressive decoding.
  SDWebImage/SDWebImageImageIOCoder.m
Labels: fix, performance

#2312 Add options to specify query cache sync/async behavior
  SDWebImage/SDImageCache.h
  SDWebImage/SDImageCache.m
  SDWebImage/SDWebImageDefine.h
Labels: refactoring

#2311 Bugfix webp encode color mode
  SDWebImage/WebP/SDImageWebPCoder.m
Labels: WebP, fix

#2315 Add `UIViewAnimationOptionAllowUserInteraction` as default options for convenient image transition
  SDWebImage/SDWebImageTransition.h
  SDWebImage/SDWebImageTransition.m
Labels: improvement

#2318 Fix WebP Encoding only works for RGBA8888 CGImage but not other color mode
  SDWebImage/SDWebImageWebPCoder.m
Labels: WebP, fix

#2327 Fix the progressive decoding bug on macOS. Including image orientation & SDAnimatedimageView
  SDWebImage/NSImage+Compatibility.m
  SDWebImage/SDAnimatedImageView.m
Labels: fix

#2328 Remove dispatch_queue_async_safe && optimize dispatch_main_async_safe
  SDWebImage/SDWebImageCompat.h
Labels: improvement

#2330 Fix that watchOS UIImage+WebCache does not mark as available and cause crash
  SDWebImage/UIImage+WebCache.m
Labels: crash

#2329 Minor optimize for dispatch_queue_async_safe
  SDWebImage/SDWebImageCompat.h
Labels: performance

#2340 Replace @synchronized with dispatch_semaphore_t in SDWebImageManager
  SDWebImage/SDWebImageManager.m
Labels: improvement

#2323 Add optimalFrameCacheSize && predrawingEnabled options for FLAnimatedImage
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
Labels: GIF, feature

#2343 Add the support for watchOS to use View Category method (sd_setImageWithURL:) on WKInterfaceImage
  Examples/SDWebImage Watch Demo Extension/InterfaceController.m
  SDWebImage/SDWebImageCompat.h
  SDWebImage/UIImageView+WebCache.h
  SDWebImage/UIImageView+WebCache.m
  SDWebImage/UIView+WebCache.h
  SDWebImage/UIView+WebCache.m
  SDWebImage/UIView+WebCacheOperation.h
  SDWebImage/UIView+WebCacheOperation.m
Labels: feature, watchOS
