Repository SDWebImage/SDWebImage, pull requests merged in 2018-07, with the labels that each got.

#2372 Follow App Store submit rule, upgrade the min Xcode version to Xcode 9.0. Using `@available` and `API_AVAILABLE` to check API availability
  Examples/SDWebImage Demo/LaunchScreen.storyboard
  README.md
  SDWebImage/SDImageCoderHelper.m
  SDWebImage/SDImageIOCoder.m
  SDWebImage/SDWebImageCompat.h
  SDWebImage/SDWebImageTransition.h
Labels: project

#2381 Fix crash when assign request property of SDWebImageDownloadToken
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloader.m
Labels: fix

#2378 Add cache control for FLAnimatedImage, this allow user to disable memory cache for associated FLAnimatedImage instance
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
  SDWebImage/SDImageCacheConfig.h
Labels: GIF

#2382 Replace runningOperations of SDWebImageManager from Array to Set
  SDWebImage/SDWebImageManager.m
Labels: refactoring

#2275 5.x CHANGELOG + Migration guide + version update
  CHANGELOG.md
  Docs/API-Diff/5.0/apidiff.css
  Docs/API-Diff/5.0/apidiff.html
  Docs/SDWebImage-5.0-Migration-guide.md
  Docs/SDWebImage.mdj
  README.md
  SDWebImage.podspec
  WebImage/Info.plist
Labels: doc, project

#2390 Keep the information about image's original compressed format, for API which only contains image but not image data to process extra logic
  SDWebImage/NSData+ImageContentType.h
  SDWebImage/NSData+ImageContentType.m
  SDWebImage/SDWebImageCodersManager.m
  SDWebImage/SDWebImageCompat.m
  SDWebImage/SDWebImageGIFCoder.m
  SDWebImage/SDWebImageImageIOCoder.m
  SDWebImage/SDWebImageWebPCoder.m
  SDWebImage/UIImage+MultiFormat.h
  SDWebImage/UIImage+MultiFormat.m
Labels: feature

#2391 Add one sync API for SDImageCache to directly get the image data from disk instead of image instance
  SDWebImage/SDImageCache.h
  SDWebImage/SDImageCache.m
Labels: feature

#2392 Replace __bridge_transfer with __bridge when convert from CFStringRef to NSString
  SDWebImage/SDImageAPNGCoder.m
  SDWebImage/SDImageCoderHelper.m
  SDWebImage/SDImageGIFCoder.m
  SDWebImage/SDImageIOCoder.m
Labels: fix

#2394 Replace __bridge_transfer with __bridge when convert from CFStringRef to NSString
  SDWebImage/SDWebImageCoderHelper.m
  SDWebImage/SDWebImageGIFCoder.m
  SDWebImage/SDWebImageImageIOCoder.m
Labels: fix

#2395 Rename `sd_UTTypeFromSDImageFormat` to `sd_UTTypeFromImageFormat`
  SDWebImage/NSData+ImageContentType.h
  SDWebImage/NSData+ImageContentType.m
  SDWebImage/SDImageAPNGCoder.m
  SDWebImage/SDImageCoderHelper.m
  SDWebImage/SDImageGIFCoder.m
  SDWebImage/SDImageIOCoder.m
  Tests/Tests/SDCategoriesTests.m
Labels: naming

#2397 Replace SDWebImageDownloaderOperation with NSOperation<SDWebImageDownloaderOperationInterface> to make generic
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloader.m
  SDWebImage/SDWebImageDownloaderOperation.h
  SDWebImage/UIView+WebCache.m
Labels: fix

#2407 5.0 Diagrams update
  Docs/Diagrams/SDWebImage.mdj
  Docs/Diagrams/SDWebImageCacheClassDiagram.png
  Docs/Diagrams/SDWebImageClassDiagram.png
  Docs/Diagrams/SDWebImageCodersClassDiagram.png
  Docs/Diagrams/SDWebImageHighLevelDiagram.jpeg
  Docs/Diagrams/SDWebImageLoaderClassDiagram.png
  Docs/Diagrams/SDWebImageManagerClassDiagram.png
  Docs/Diagrams/SDWebImageSequenceDiagram.png
  Docs/Diagrams/SDWebImageTopLevelClassDiagram.png
  Docs/SDWebImage.mdj
  Docs/SDWebImageClassDiagram.png
  Docs/SDWebImageSequenceDiagram.png
  README.md
Labels: doc
