Repository SDWebImage/SDWebImage, pull requests merged in 2018-06, with the labels that each got.

#2348 Fix that WebP (including Animated WebP) decoding issue on iOS 12.
  SDWebImage/SDWebImageWebPCoder.m
Labels: WebP, fix

#2326 Renaming image loader
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
  SDWebImage/MapKit/MKAnnotationView+WebCache.h
  SDWebImage/MapKit/MKAnnotationView+WebCache.m
  SDWebImage/NSButton+WebCache.h
  SDWebImage/NSButton+WebCache.m
  SDWebImage/SDAnimatedImageView+WebCache.h
  SDWebImage/SDAnimatedImageView+WebCache.m
  SDWebImage/SDImageLoader.h
  SDWebImage/SDImageLoader.m
  SDWebImage/SDImageLoadersManager.h
  SDWebImage/SDImageLoadersManager.m
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloader.m
  SDWebImage/SDWebImageDownloaderOperation.m
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageManager.m
  SDWebImage/UIButton+WebCache.h
  SDWebImage/UIButton+WebCache.m
  SDWebImage/UIImageView+HighlightedWebCache.h
  SDWebImage/UIImageView+HighlightedWebCache.m
  SDWebImage/UIImageView+WebCache.h
  SDWebImage/UIImageView+WebCache.m
  SDWebImage/UIView+WebCache.h
  SDWebImage/UIView+WebCache.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImageTestLoader.h
  Tests/Tests/SDWebImageTestLoader.m
  WebImage/SDWebImage.h
Labels: naming

#2359 fix that SDImageCache does not use transformed key to query cache when provide a transformer
  SDWebImage/SDImageCache.m
Labels: bug

#2361 Refactor the UIImage+MultiFormat and GIF/WebP category
  SDWebImage/UIImage+GIF.h
  SDWebImage/UIImage+GIF.m
  SDWebImage/UIImage+MultiFormat.h
  SDWebImage/UIImage+MultiFormat.m
  SDWebImage/WebP/UIImage+WebP.h
  SDWebImage/WebP/UIImage+WebP.m
  Tests/Tests/SDCategoriesTests.m
Labels: refactoring

#2360 Add the `SDWebImageContextStoreCacheType` context option to specify target cache type when the image is downloaded by manager and will store to cache
  SDWebImage/SDWebImageDefine.h
  SDWebImage/SDWebImageDefine.m
  SDWebImage/SDWebImageManager.m
Labels: feature

#2357 Enable to change clear cache option
  SDWebImage/SDImageCache.m
  SDWebImage/SDImageCacheConfig.h
  SDWebImage/SDImageCacheConfig.m
Labels: feature

#2362 Add one convenient method to pass context arg without completed block for all View Category
  SDWebImage/MapKit/MKAnnotationView+WebCache.h
  SDWebImage/MapKit/MKAnnotationView+WebCache.m
  SDWebImage/NSButton+WebCache.h
  SDWebImage/NSButton+WebCache.m
  SDWebImage/SDAnimatedImageView+WebCache.h
  SDWebImage/SDAnimatedImageView+WebCache.m
  SDWebImage/UIButton+WebCache.h
  SDWebImage/UIButton+WebCache.m
  SDWebImage/UIImageView+HighlightedWebCache.h
  SDWebImage/UIImageView+HighlightedWebCache.m
  SDWebImage/UIImageView+WebCache.h
  SDWebImage/UIImageView+WebCache.m
Labels: improvement

#2363 Fix that UIImage+Transform on macOS to use BGRA8888 instead of ARGB8888, as Apple's doc
  SDWebImage/UIImage+Transform.m
Labels: fix

#2364 Renaming UIImage+WebCache to the correct naming UIImage+Metadata, make clear of the category usage
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/NSImage+Compatibility.h
  SDWebImage/SDAnimatedImage.m
  SDWebImage/SDAnimatedImageView.h
  SDWebImage/SDAnimatedImageView.m
  SDWebImage/SDImageAPNGCoder.m
  SDWebImage/SDImageCache.m
  SDWebImage/SDImageCacheDefine.m
  SDWebImage/SDImageCoderHelper.m
  SDWebImage/SDImageCodersManager.m
  SDWebImage/SDImageFrame.h
  SDWebImage/SDImageGIFCoder.m
  SDWebImage/SDImageLoader.m
  SDWebImage/SDWebImageDefine.h
  SDWebImage/SDWebImageDefine.m
  SDWebImage/SDWebImageManager.m
  SDWebImage/UIImage+Metadata.h
  SDWebImage/UIImage+Metadata.m
  SDWebImage/UIImage+Transform.m
  SDWebImage/WebP/SDImageWebPCoder.m
  WebImage/SDWebImage.h
Labels: naming
