Repository SDWebImage/SDWebImage, pull requests merged in 2018-08, with the labels that each got.

#2414 Fix that downloader options about image decoding is not correctly set
  SDWebImage/SDImageCacheDefine.m
  SDWebImage/SDImageLoader.m
  SDWebImage/SDWebImageDownloader.m
Labels: fix

#2433 Fix cache migration when dstPath intermediate directories not exist
  SDWebImage/SDDiskCache.h
  SDWebImage/SDDiskCache.m
Labels: fix

#2435 Fix a race condition during progressive animation load in SDAnimatedImageView
  SDWebImage/SDAnimatedImageView.m
Labels: fix

#2437 Fix the bug that progress indicator on macOS stop at 1% but not 100% when download finished
  SDWebImage/SDWebImageIndicator.m
  SDWebImage/UIView+WebCache.m
Labels: fix

#2432 Fix that the minimumProgressInterval should always callback the final finished progress but not ignore it
  SDWebImage/SDWebImageDownloaderConfig.h
  SDWebImage/SDWebImageDownloaderOperation.h
  SDWebImage/SDWebImageDownloaderOperation.m
  Tests/Tests/SDWebImageDownloaderTests.m
Labels: fix

#2450 Fix the test case testFLAnimatedImageViewSetImageWithURL because of remote resource is not available
  Tests/Tests/SDCategoriesTests.m
  Tests/Tests/SDTestCase.h
  Tests/Tests/SDTestCase.m
Labels: test

#2438 Add the test cases for View Transition and View Indicator, both iOS && macOS
  Tests/Tests/SDAnimatedImageTest.m
  Tests/Tests/SDTestCase.h
  Tests/Tests/SDWebCacheCategoriesTests.m
Labels: test

#2434 Add more tests for image decoding/encoding part
  .travis.yml
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/Images/TestImage.heic
  Tests/Tests/Images/TestImage.heif
  Tests/Tests/SDAnimatedImageTest.m
  Tests/Tests/SDImageCacheTests.m
  Tests/Tests/SDImageCoderTests.m
  Tests/Tests/SDTestCase.h
  Tests/Tests/SDTestCase.m
  Tests/Tests/SDWebCacheCategoriesTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImageManagerTests.m
Labels: test

#2451 Fix the bug that `SDWebImageContextCacheKeyFilter` wrongly be used as cache serializer and cause crash
  SDWebImage/SDWebImageManager.m
  Tests/Tests/SDWebImageManagerTests.m
Labels: bug

#2452 Adopt all the protocol APIs which contains getter value to use property instead, to make the API easy to use or Swift user
  SDWebImage/SDAnimatedImage.h
  SDWebImage/SDDiskCache.h
  SDWebImage/SDDiskCache.m
  SDWebImage/SDImageCoder.h
  SDWebImage/SDImageTransformer.h
  SDWebImage/SDWebImageDownloaderOperation.h
  SDWebImage/SDWebImageIndicator.h
  Tests/Tests/SDWebImageTestCache.m
Labels: improvement

#2462 Fix resource key invalid when clean cached disk file
  SDWebImage/SDDiskCache.m
Labels: fix

#2463 Fix resource key invalid when clean cached disk file
  SDWebImage/SDImageCache.m
Labels: fix

#2461 Add no expiration file support of disk cache
  SDWebImage/SDDiskCache.m
  SDWebImage/SDImageCacheConfig.h
Labels: feature

#2466 Add protect when custom animated image class image data is nil during progressive animation check
  SDWebImage/SDAnimatedImageView.m
Labels: fix
