Repository SDWebImage/SDWebImage, pull requests merged in 2019-06, with the labels that each got.

#2742 Fix the Demo WebP coder import issue when enable modular headers
  Examples/SDWebImage Demo/MasterViewController.m
  Examples/SDWebImage OSX Demo/ViewController.m
  Examples/SDWebImage TV Demo/ViewController.m
  Examples/SDWebImage Watch Demo Extension/InterfaceController.m
Labels: demo

#2741 Fix the Static Library target issue of headers, which cause the integrated application failed to Archive because of copied headers
  .travis.yml
  SDWebImage.xcodeproj/project.pbxproj
Labels: project

#2745 Fix the SDAnimatedImageRep which use the deprecated API and cause compile issue on Xcode 11
  SDWebImage/SDAnimatedImageRep.m
Labels: fix, macOS

#2749 Temporary fix for CocoaPods modular headers warning because their bug to cause the custom modulemap been placed under Pods Private directory but not Public directory, unlike the default generated modulemap
  SDWebImage.podspec
  SDWebImage.xcodeproj/project.pbxproj
  WebImage/SDWebImage.modulemap
Labels: CocoaPods

#2736 Supports global control on options and context for individual image request
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageManager.m
  SDWebImage/SDWebImageOptionsProcessor.h
  SDWebImage/SDWebImageOptionsProcessor.m
  Tests/Tests/SDWebImageManagerTests.m
  WebImage/SDWebImage.h
Labels: feature

#2753 Feature supports dynamic style indicator for iOS 13, fix indicator color on macOS 10.14+
  Examples/SDWebImage OSX Demo/ViewController.m
  SDWebImage/SDWebImageIndicator.h
  SDWebImage/SDWebImageIndicator.m
Labels: feature

#2760 Fix the Clang Static Analysis warning of `addEntriesFromDictionary:` API
  SDWebImage/SDWebImageManager.m
Labels: fix

#2761 Update the Travis-CI environment to Xcode 10.2 (Swift 5)
  .travis.yml
  Examples/Podfile
  Examples/SDWebImage Demo.xcodeproj/project.pbxproj
  Podfile
  SDWebImage.xcworkspace/contents.xcworkspacedata
  Tests/Podfile
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Labels: project

#2763 Change that the `sd_imageProgress` property to not auto-create instance by framework
  SDWebImage/UIView+WebCache.h
  SDWebImage/UIView+WebCache.m
Labels: important

#2756 Add support for Swift Package Manager
  .gitignore
  .travis.yml
  Package.swift
Labels: swift

#2773 Delete unnecessary code
  SDWebImage/SDWebImageDownloaderOperation.m
Labels: gardening
