Repository SDWebImage/SDWebImage, pull requests merged in 2019-05, with the labels that each got.

#2711 Added many test case to ensure the code behavior and coverage
  Configs/Test-Shared.xcconfig
  SDWebImage/SDWebImageDefine.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/SDAnimatedImageTest.m
  Tests/Tests/SDCategoriesTests.m
  Tests/Tests/SDImageCacheTests.m
  Tests/Tests/SDImageCoderTests.m
  Tests/Tests/SDImageTransformerTests.m
  Tests/Tests/SDUtilsTests.m
  Tests/Tests/SDWebCacheCategoriesTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImagePrefetcherTests.m
Labels: test

#2722 Update the documentation coverage for jazzy. Use the correct format to provide class/protocol/type API Documentation
  SDWebImage/NSButton+WebCache.h
  SDWebImage/NSData+ImageContentType.h
  SDWebImage/NSImage+Compatibility.h
  SDWebImage/SDAnimatedImage.h
  SDWebImage/SDAnimatedImageRep.h
  SDWebImage/SDAnimatedImageView+WebCache.h
  SDWebImage/SDDiskCache.h
  SDWebImage/SDImageCache.h
  SDWebImage/SDImageCacheConfig.h
  SDWebImage/SDImageCacheDefine.h
  SDWebImage/SDImageCachesManager.h
  SDWebImage/SDImageCoderHelper.h
  SDWebImage/SDImageFrame.h
  SDWebImage/SDImageGraphics.h
  SDWebImage/SDImageLoader.h
  SDWebImage/SDImageLoadersManager.h
  SDWebImage/SDImageTransformer.h
  SDWebImage/SDMemoryCache.h
  SDWebImage/SDWebImageCacheKeyFilter.h
  SDWebImage/SDWebImageCacheSerializer.h
  SDWebImage/SDWebImageDefine.h
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloaderConfig.h
  SDWebImage/SDWebImageDownloaderOperation.h
  SDWebImage/SDWebImageDownloaderRequestModifier.h
  SDWebImage/SDWebImageError.h
  SDWebImage/SDWebImageIndicator.h
  SDWebImage/SDWebImageManager.h
  SDWebImage/SDWebImageOperation.h
  SDWebImage/SDWebImagePrefetcher.h
  SDWebImage/SDWebImageTransition.h
  SDWebImage/UIButton+WebCache.h
  SDWebImage/UIImage+ForceDecode.h
  SDWebImage/UIImage+GIF.h
  SDWebImage/UIImage+MemoryCacheCost.h
  SDWebImage/UIImage+Metadata.h
  SDWebImage/UIImage+MultiFormat.h
  SDWebImage/UIImageView+WebCache.h
  SDWebImage/UIView+WebCache.h
  SDWebImage/UIView+WebCacheOperation.h
Labels: documents

#2728 Fix that SDAnimatedImageView initWithImage will skip the initialize logic and crash
  SDWebImage/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: fix

#2725 fix issues: SDWebImageDecodeFirstFrameOnly flag is ignored when image loaded from cache
  SDWebImage/SDImageCache.m
Labels: Good first issue, animated image

#2737 Fix get button background image operation key bug
  SDWebImage/UIButton+WebCache.m
  Tests/Tests/SDImageTransformerTests.m
  Tests/Tests/SDWebCacheCategoriesTests.m
Labels: fix

#2739 Fix that `CGImageDestinationCreateWithData` 0 count arg will log a warning
  SDWebImage/SDImageAPNGCoder.m
  SDWebImage/SDImageGIFCoder.m
Labels: fix

#2740 Fix the example NSLog issue, and replace the unavailable test image dataset
  Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage OSX Demo.xcscheme
  Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage TV Demo.xcscheme
  Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage Watch Demo.xcscheme
  Examples/SDWebImage Demo.xcodeproj/xcshareddata/xcschemes/SDWebImage iOS Demo.xcscheme
  Examples/SDWebImage Demo/MasterViewController.m
  Examples/SDWebImage TV Demo/ViewController.m
  Tests/SDWebImage Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
  Tests/Tests/SDWebImageManagerTests.m
Labels: demo
