Repository SDWebImage/SDWebImage, pull requests merged in 2019-01, with the labels that each got.

#2568 Use the memory bytes size, instead of pixel size to calculate the memory cost function
  SDWebImage/SDAnimatedImage.m
  SDWebImage/SDImageCacheConfig.h
  SDWebImage/UIImage+MemoryCacheCost.h
  SDWebImage/UIImage+MemoryCacheCost.m
Labels: refactoring

#2585 Fix that WebP image with ICC Profile does not show color correctly, should use the profile colorspace instead of device colorspace
  SDWebImage/SDWebImageWebPCoder.m
Labels: WebP

#2592 Fix that WebP decoder in master branch, does not consider the global `shouldDecompressImages` config and always do pre-draw for static WebP images.
  SDWebImage/SDWebImageDownloaderOperation.m
  SDWebImage/SDWebImageWebPCoder.m
Labels: WebP, fix

#2558 Fix the current image cost (pixels) for FLAnimatedImage
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
Labels: GIF

#2588 Fix the FLAnimatedImage compatible code issue by introduce a private API
  SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m
  SDWebImage/UIView+WebCache.h
  SDWebImage/UIView+WebCache.m
  Tests/Tests/SDCategoriesTests.m
Labels: GIF

#2604 Revert modular framework
  README.md
  SDWebImage.podspec
Labels: CocoaPods, project

#2606 Fix shouldDecode check when image format is GIF
  SDWebImage/SDWebImageDownloaderOperation.m
Labels: GIF, performance

#2607 Fix modify data pointer if webp image scaled down
  SDWebImage/SDWebImageWebPCoder.m
Labels: WebP, fix
