Repository SDWebImage/SDWebImage, pull requests merged in 2019-12, with the labels that each got.

#2900 Add `SDWebImageWaitStoreCache`, which wait for all the async disk cache written finished and then callback, useful for advanced user who want to touch the cache right in completion block
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageManager.m
Labels: feature

#2899 Support using NSCache delegate with SDMemoryCache default implementation
  SDWebImage/Core/SDMemoryCache.h
  SDWebImage/Core/SDMemoryCache.m
Labels: improvement

#2902 Using one global function to ensure we always sync all the UIImage category assocaited object status correctly inside our framework
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Core/SDImageCoderHelper.m
  SDWebImage/Core/SDWebImageDefine.m
  SDWebImage/Core/SDWebImageManager.m
  SDWebImage/Private/SDAssociatedObject.h
  SDWebImage/Private/SDAssociatedObject.m
Labels: fix

#2903 Fix the thread safe issue with Downloader and DownloaderOperation during cancel
  SDWebImage/Core/SDWebImageDefine.m
  SDWebImage/Core/SDWebImageDownloader.m
Labels: fix

#2907 Performance - Using UIGraphicsImageRenderer on iOS 10+, save memory when image bitmap is RGB(-25%) or Grayscale(-75%)
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Core/SDGraphicsImageRenderer.h
  SDWebImage/Core/SDGraphicsImageRenderer.m
  SDWebImage/Core/SDImageGraphics.h
  SDWebImage/Core/UIImage+Transform.m
  Tests/Tests/SDImageTransformerTests.m
  Tests/Tests/SDUtilsTests.m
  WebImage/SDWebImage.h
Labels: performance

#2917 Fix the issue that "There may be no complete callback when download the picture of the local path"
  SDWebImage/Core/SDWebImageDownloader.m
Labels: fix

#2916 [4.x] Fix the issue that "There may be no complete callback when download the picture of the local path"
  SDWebImage/SDWebImageDownloader.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Labels: fix

#2915 Support to use the creation date and the change date to determine the disk cache expire date compare
  SDWebImage/Core/SDDiskCache.m
  SDWebImage/Core/SDImageCacheConfig.h
Labels: feature
