Repository SDWebImage/SDWebImage, pull requests merged in 2019-08, with the labels that each got.

#2801 Add a new option `SDWebImageMatchAnimatedImageClass`, to ensure we always match the custom image class instead of UIImage/NSImage class
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDImageCacheDefine.m
  SDWebImage/Core/SDImageLoader.m
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageDownloader.h
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageDownloaderOperation.m
  Tests/Tests/SDImageCacheTests.m
Labels: feature

#2802 Add missing nullable and nonnull attributes
  SDWebImage/Core/NSImage+Compatibility.m
  SDWebImage/Core/UIImage+ForceDecode.m
  SDWebImage/Core/UIImage+Transform.m
Labels: gardening

#2692 Ensure we always callback user's completion block even when cancelled with `SDWebImageErrorCancelled` error code
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageDownloaderOperation.m
  SDWebImage/Core/SDWebImageError.h
  SDWebImage/Core/SDWebImageManager.m
  Tests/Tests/SDWebCacheCategoriesTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImageManagerTests.m
  Tests/Tests/SDWebImagePrefetcherTests.m
Labels: fix, important

#2808 Feature: Support UIKit for macOS (Catalyst)
  .travis.yml
  Configs/Module-Shared.xcconfig
  Examples/SDWebImage Demo.xcodeproj/project.pbxproj
  SDWebImage.podspec
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage.xcworkspace/contents.xcworkspacedata
  SDWebImage/Core/SDAnimatedImageView.m
  SDWebImage/Core/SDImageCacheDefine.m
  SDWebImage/Core/SDImageLoader.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: catalyst, feature, macOS

#2815 Support to clear frame buffer or reset frame index when stopped for SDAnimatedImageView
  SDWebImage/Core/SDAnimatedImageView.h
  SDWebImage/Core/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: feature
