Repository SDWebImage/SDWebImage, pull requests merged in 2019-03, with the labels that each got.

#2631 Fix the issue that SDWebImagePrefetch in 5.x, will submit all prefetch URLs to manager without any concurrent limit
  SDWebImage.podspec
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Private/SDAsyncBlockOperation.h
  SDWebImage/Private/SDAsyncBlockOperation.m
  SDWebImage/SDWebImagePrefetcher.h
  SDWebImage/SDWebImagePrefetcher.m
Labels: fix

#2634 Move some internal classes into private header files, make it easy to maintain the code
  Examples/SDWebImage Demo.xcodeproj/project.pbxproj
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Private/NSBezierPath+RoundedCorners.h
  SDWebImage/Private/NSBezierPath+RoundedCorners.m
  SDWebImage/Private/SDImageAPNGCoderInternal.h
  SDWebImage/Private/SDImageAssetManager.h
  SDWebImage/Private/SDImageAssetManager.m
  SDWebImage/Private/SDImageCachesManagerOperation.h
  SDWebImage/Private/SDImageCachesManagerOperation.m
  SDWebImage/Private/SDImageGIFCoderInternal.h
  SDWebImage/Private/SDWeakProxy.h
  SDWebImage/Private/SDWeakProxy.m
  SDWebImage/Private/UIColor+HexString.h
  SDWebImage/Private/UIColor+HexString.m
  SDWebImage/SDAnimatedImage.m
  SDWebImage/SDAnimatedImageRep.m
  SDWebImage/SDAnimatedImageView.m
  SDWebImage/SDImageCachesManager.m
  SDWebImage/SDImageTransformer.m
  SDWebImage/UIImage+Transform.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Labels: project

#2635 Fix the current transformer cache key generating rules, try to keep the image file extension
  SDWebImage/SDImageTransformer.m
  Tests/Tests/SDImageTransformerTests.m
Labels: fix

#2645 Fix prefetch hung up
  SDWebImage/Private/SDAsyncBlockOperation.m
  SDWebImage/SDWebImagePrefetcher.m
Labels: fix

#2633 Define SDWebImageDownloader convenience method
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloader.m
Labels: feature

#2650 Rename the SDImageLoaderProtocol method naming to avoid the Selector conflict with SDWebImageManager and cause misunderstanding usage
  SDWebImage/SDImageLoader.h
  SDWebImage/SDImageLoadersManager.m
  SDWebImage/SDWebImageDownloader.m
  SDWebImage/SDWebImageManager.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImageTestLoader.m
Labels: naming

#2652 Fix the issue cause build failure for Xcode 10.2
  Configs/Module-Shared.xcconfig
  Configs/Test-Debug.xcconfig
  Configs/Test-Release.xcconfig
  Examples/SDWebImage Demo.xcodeproj/project.pbxproj
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage.xcworkspace/contents.xcworkspacedata
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
Labels: project

#2657 Fix a crash, when SDAnimatedImageView dealloc, displayLinkContext in the async block will be a bad pointer
  SDWebImage/SDAnimatedImageView.m
Labels: fix, macOS

#2658 Remove the unused hack of intrinsicContentSize for SDAnimatedImageView
  SDWebImage/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: fix

#2659 Bugfix macOS related small improvement for SDAnimatedImageView
  SDWebImage/SDAnimatedImageView.m
Labels: macOS

#2660 Fix the thread safe issue of caches manager and specify the default caches array value.
  SDWebImage/SDImageCachesManager.h
  SDWebImage/SDImageCachesManager.m
  SDWebImage/SDImageCodersManager.h
  SDWebImage/SDImageCodersManager.m
  SDWebImage/SDImageLoadersManager.h
  SDWebImage/SDImageLoadersManager.m
  Tests/Tests/SDImageCacheTests.m
Labels: fix

#2648 Filter the error domain with NSURLErrorDomain before checking the URL Error Codes
  SDWebImage/SDWebImageManager.m
Labels: fix
