Repository SDWebImage/SDWebImage, pull requests merged in 2019-04, with the labels that each got.

#2661 Fix that `SDWebImageDownloadStartNotification` declare twice in header files
  SDWebImage/SDWebImageDownloader.h
  SDWebImage/SDWebImageDownloader.m
  SDWebImage/SDWebImageDownloaderOperation.h
  SDWebImage/SDWebImageDownloaderOperation.m
Labels: fix

#2667 Guarantee thread-safe for SDImageCachesManager SDImageCodersManager SDImageLoadersManager
  SDWebImage/SDImageCachesManager.h
  SDWebImage/SDImageCachesManager.m
  SDWebImage/SDImageCodersManager.h
  SDWebImage/SDImageCodersManager.m
  SDWebImage/SDImageLoadersManager.h
  SDWebImage/SDImageLoadersManager.m
Labels: fix

#2668 Fix the black list error domain should filter specify SDWebImageErrorDomain codes which is indeed un-recoverable
  SDWebImage/SDImageLoader.h
  SDWebImage/SDImageLoadersManager.m
  SDWebImage/SDWebImageDownloader.m
  SDWebImage/SDWebImageManager.m
  Tests/Tests/SDWebImageTestLoader.m
Labels: fix

#2673 Fix rounded corner bug which leads to image upside down
  SDWebImage/UIImage+Transform.m
  Tests/Tests/Images/TestImage.png
  Tests/Tests/SDImageTransformerTests.m
Labels: fix

#2674 Fix tint image bug which leads to image upside down
  SDWebImage/UIImage+Transform.m
  Tests/Tests/SDImageTransformerTests.m
Labels: fix

#2685 Delete prepare shell when archive static library and update manual installation doc.
  Docs/ManualInstallation.md
  SDWebImage.xcodeproj/project.pbxproj
Labels: documents

#2691 Fixes crash for apng coder when properties are nil
  SDWebImage/SDImageAPNGCoder.m
Labels: fix

#2706 Fix the bug of SDAnimatedImageView, which can not render the normal NSImage (including animated image) at all. Only `SDAnimatedImage` can be rendered
  Examples/SDWebImage OSX Demo/ViewController.m
  SDWebImage/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: fix, macOS

#2708 Fix that `CGImageCreateDecoded:orientation:` use the wrong aspect ratio when orientation is left/leftMirrored/right/rightMirrored
  SDWebImage/SDImageCoderHelper.m
  SDWebImage/UIImage+Transform.m
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/Images/TestEXIF.png
  Tests/Tests/SDImageTransformerTests.m
Labels: bug, test

#2710 Replace if judge with MAX() function in scale less than 1
  SDWebImage/SDAnimatedImage.m
  SDWebImage/SDImageAPNGCoder.m
  SDWebImage/SDImageCacheDefine.m
  SDWebImage/SDImageCoderHelper.m
  SDWebImage/SDImageGIFCoder.m
  SDWebImage/SDImageIOCoder.m
  SDWebImage/SDImageLoader.m
  SDWebImage/UIImage+MultiFormat.m
Labels: gardening
