Repository SDWebImage/SDWebImage, pull requests merged in 2020-05, with the labels that each got.

#2999 Fix the issue that NSOperation conforms to `SDWebImageOperation` check failed. And fix the SDAsyncBlockOperation cancel logic
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Core/SDWebImageOperation.m
  SDWebImage/Core/SDWebImagePrefetcher.m
  SDWebImage/Private/SDAsyncBlockOperation.m
  Tests/Tests/SDWebImageDownloaderTests.m
Labels: bug, important

#2997 Mark the black list formal error code, support remove the failed URL from black list
  SDWebImage/Core/SDWebImageError.h
  SDWebImage/Core/SDWebImageManager.h
  SDWebImage/Core/SDWebImageManager.m
Labels: feature

#3005 Polish the error description between image decode failed and image size is 0
  SDWebImage/Core/SDWebImageDownloaderOperation.m
Labels: improvement

#3003 Added autoplay control property to AnimatedImageView (autoPlayAnimatedImage)
  SDWebImage/Core/SDAnimatedImageView.h
  SDWebImage/Core/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: animated image, feature

#3015 Fix the issue that ImageIO max pixel size larger than image size will cause a upscale
  SDWebImage/Core/SDImageIOCoder.m
Labels: bug
