Repository SDWebImage/SDWebImage, pull requests merged in 2020-11, with the labels that each got.

#3113 Add animationImages support when using SDAnimatedImageView
  SDWebImage/Core/SDAnimatedImageView.h
  SDWebImage/Core/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: animated image, fix

#3129 Added the options and context arg for Image Loader custom protoocl, this can be used for advanced user to grab and check for context for current loading URL to process the logic
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageIOAnimatedCoder.m
  SDWebImage/Core/SDImageLoader.h
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageManager.m
  Tests/Tests/SDWebImageTestLoader.m
Labels: feature

#3128 Replace all current dispatch_semaphore usage into the os_unfair_lock, use OSSpinLock for lower firmware
  SDWebImage/Core/SDAnimatedImagePlayer.m
  SDWebImage/Core/SDImageCachesManager.m
  SDWebImage/Core/SDImageCodersManager.m
  SDWebImage/Core/SDImageLoadersManager.m
  SDWebImage/Core/SDMemoryCache.m
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageManager.m
  SDWebImage/Core/SDWebImagePrefetcher.m
  SDWebImage/Private/SDImageAssetManager.m
  SDWebImage/Private/SDImageCachesManagerOperation.m
  SDWebImage/Private/SDInternalMacros.h
Labels: performance

#3115 Add some animation playback mode
  SDWebImage/Core/SDAnimatedImagePlayer.h
  SDWebImage/Core/SDAnimatedImagePlayer.m
  SDWebImage/Core/SDAnimatedImageView.h
  SDWebImage/Core/SDAnimatedImageView.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: animated image, feature

#3118 Shorten code indentation
  SDWebImage/Core/SDImageCache.m
Labels: gardening

#3130 Bumped the min deployment target version to iOS 9, macOS 10.11. Bumped the min Xcode version to Xcode 11
  Configs/Module-Shared.xcconfig
  Examples/SDWebImage Demo/SDWebImage Demo-Prefix.pch
  Package.swift
  Podfile
  README.md
  SDWebImage.podspec
  SDWebImage/Core/SDImageAPNGCoder.m
  SDWebImage/Core/SDImageHEICCoder.m
  SDWebImage/Core/SDWebImageDownloaderOperation.m
  SDWebImage/Core/SDWebImageIndicator.m
  Tests/Tests/SDWebImageDownloaderTests.m
Labels: project, xcode

#2946 Totally remove the MapKit integration, including Source Code, Subspec, SwiftPM, fix the issue of SwiftPM on Xcode 11.4 Beta, make it scalable
  .travis.yml
  Examples/SDWebImage Demo.xcodeproj/project.pbxproj
  Package.swift
  Podfile
  README.md
  SDWebImage.podspec
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImageMapKit.xcscheme
  SDWebImageMapKit/MapKit/MKAnnotationView+WebCache.h
  SDWebImageMapKit/MapKit/MKAnnotationView+WebCache.m
  SDWebImageMapKit/include/SDWebImageMapKit/MKAnnotationView+WebCache.h
  SDWebImageMapKit/include/SDWebImageMapKit/SDWebImageMapKit.h
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/SDAnimatedImageTest.m
  Tests/Tests/SDWebCacheCategoriesTests.m
  WebImage/SDWebImage.h
  WebImage/SDWebImageMapKit.h
Labels: important, project
