Repository SDWebImage/SDWebImage, pull requests merged in 2020-06, with the labels that each got.

#3026 Fixing Typos throughout project
  Docs/SDWebImage-5.0-Migration-guide.md
  SDWebImage/Core/NSData+ImageContentType.h
  SDWebImage/Core/SDAnimatedImage.h
  SDWebImage/Core/SDAnimatedImagePlayer.h
  SDWebImage/Core/SDAnimatedImagePlayer.m
  SDWebImage/Core/SDAnimatedImageRep.m
  SDWebImage/Core/SDAnimatedImageView.m
  SDWebImage/Core/SDDiskCache.m
  SDWebImage/Core/SDImageAPNGCoder.m
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDImageCacheConfig.h
  SDWebImage/Core/SDImageCacheDefine.h
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageCoderHelper.h
  SDWebImage/Core/SDImageCoderHelper.m
  SDWebImage/Core/SDImageHEICCoder.m
  SDWebImage/Core/SDImageIOAnimatedCoder.h
  SDWebImage/Core/SDImageLoader.h
  SDWebImage/Core/SDImageLoadersManager.h
  SDWebImage/Core/SDImageTransformer.h
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageDownloader.h
  SDWebImage/Core/SDWebImageDownloaderConfig.h
  SDWebImage/Core/SDWebImageDownloaderDecryptor.h
  SDWebImage/Core/SDWebImageDownloaderOperation.h
  SDWebImage/Core/SDWebImageDownloaderOperation.m
  SDWebImage/Core/SDWebImageDownloaderRequestModifier.h
  SDWebImage/Core/SDWebImageDownloaderResponseModifier.h
  SDWebImage/Core/SDWebImageError.h
  SDWebImage/Core/SDWebImageManager.h
  SDWebImage/Core/SDWebImageManager.m
  SDWebImage/Core/SDWebImagePrefetcher.h
  SDWebImage/Core/SDWebImageTransition.h
  SDWebImage/Core/UIImage+GIF.h
  SDWebImage/Core/UIImage+MemoryCacheCost.h
  SDWebImage/Core/UIImage+Transform.h
  SDWebImage/Core/UIView+WebCache.h
  SDWebImage/Core/UIView+WebCacheOperation.h
  SDWebImage/Core/UIView+WebCacheOperation.m
Labels: documents

#3010 Update the Travis-CI to use Catalina and enable macCatalyst test case
  .travis.yml
Labels: catalyst, project

#3027 Added the convenient transition with duration APIs
  SDWebImage/Core/SDWebImageTransition.h
  SDWebImage/Core/SDWebImageTransition.m
Labels: feature

#3030 SDAnimatedImagePlayer seek returning nil image fix
  SDWebImage/Core/SDAnimatedImagePlayer.m
  Tests/Tests/SDAnimatedImageTest.m
Labels: Behavior Changes

#3037 Fix the issue that the NSURLRequest method should not be nil, which may cause Crash
  SDWebImage/Core/SDWebImageDownloaderRequestModifier.m
Labels: crash, fix

#3038 Change to use kCGImageSourceCreateThumbnailFromImageAlways to solve the issue when HEIC/JPEG contains an embed thumbnail but its size is much smaller than provided `maxPixelSize`
  SDWebImage/Core/SDImageIOAnimatedCoder.m
Labels: apple bug, fix

#3039 Fix the `maxPixelSize` logic issue will cause a upscale in SDImageIOAnimatedCoder
  SDWebImage/Core/SDImageIOAnimatedCoder.m
Labels: ImageIO, fix

#3043 Fix the issue that SDAnimatedImageView can not render static image on iOS 14.
  SDWebImage/Core/SDAnimatedImageView.m
Labels: animated image, fix
