Repository SDWebImage/SDWebImage, pull requests merged in 2020-04, with the labels that each got.

#2967 Simplify the xattr helper method's code with modern Objective-C syntax
  SDWebImage/Private/SDFileAttributeHelper.m
Labels: gardening

#2968 Added new query cache type support, including the SDImageCache API and context option
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDImageCacheDefine.h
  SDWebImage/Core/SDImageCachesManager.m
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageDefine.m
  SDWebImage/Core/SDWebImageManager.m
  Tests/Tests/SDImageCacheTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
  Tests/Tests/SDWebImageManagerTests.m
  Tests/Tests/SDWebImageTestCache.h
  Tests/Tests/SDWebImageTestCache.m
  Tests/Tests/SDWebImageTestLoader.h
  Tests/Tests/SDWebImageTestLoader.m
Labels: feature

#2966 Refactory the current thumbnail && transformer about cache key. Developer should have the API to calcualte the cache key from thumbnail or transformer, not hard-coded.
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageTransformer.h
  SDWebImage/Core/SDImageTransformer.m
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageManager.h
  SDWebImage/Core/SDWebImageManager.m
  Tests/Tests/SDWebImageManagerTests.m
Labels: Behavior Changes, bug

#2971 Fix the issue for Carthage/SwiftPM framework version symbols, this should match the framework name SDWebImage, or will get a link error when used
  WebImage/SDWebImage.h
Labels: Carthage, bad install, swiftpm

#2972 Feature supports encoding options like max file size, max pixel size, as well as background color when using JPEG for alpha image
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageCoder.m
  SDWebImage/Core/SDImageIOAnimatedCoder.m
  SDWebImage/Core/SDImageIOCoder.m
  Tests/Tests/SDImageCoderTests.m
Labels: feature

#2973 Change the behavior to return the abstract type for unknown image format, this can solve the accident issue for custom coder who provide a new format
  SDWebImage/Core/NSData+ImageContentType.h
  SDWebImage/Core/NSData+ImageContentType.m
  Tests/Tests/SDCategoriesTests.m
Labels: Behavior Changes

#2974 Fix the wrong value assignment for SDAnimatedImageView code on macOS, warning
  SDWebImage/Core/SDAnimatedImageView.m
Labels: warning

#2982 Fix that when first play animated image and use maxBufferSize to 0, the calculation does not works (The CGImage is nil)
  SDWebImage/Core/SDAnimatedImagePlayer.m
Labels: OOM, animated image, bug

#2983 Rename the private header `UIColor+HexString` and `NSBezierPath+SDRoundedCorners` with SD prefix, to avoid the conflict when using CocoaPods
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Core/SDImageTransformer.m
  SDWebImage/Core/UIImage+Transform.m
  SDWebImage/Private/NSBezierPath+SDRoundedCorners.h
  SDWebImage/Private/NSBezierPath+SDRoundedCorners.m
  SDWebImage/Private/UIColor+SDHexString.h
  SDWebImage/Private/UIColor+SDHexString.m
  Tests/Tests/SDImageCoderTests.m
  Tests/Tests/SDImageTransformerTests.m
  Tests/Tests/SDUtilsTests.m
Labels: CocoaPods, project

#2977 SDAnimatedImageView animation rendering should not use CGContext force decoding, use `kCGImageSourceShouldCacheImmediately` instead which can avoid OOM for large number of GIFs
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageCoderHelper.m
  SDWebImage/Core/SDImageIOAnimatedCoder.m
  SDWebImage/Core/SDImageIOCoder.m
  SDWebImage/Private/SDImageIOAnimatedCoderInternal.h
  Tests/SDWebImage Tests.xcodeproj/project.pbxproj
  Tests/Tests/Images/TestImageLarge.png
  Tests/Tests/SDImageCoderTests.m
Labels: GIF, animated image, fix

#2989 Fix the encoding options which does not passthrough the correct value to ImageIO
  SDWebImage/Core/SDImageIOAnimatedCoder.m
Labels: fix

#2988 Feature: Encoding options supports embed thumbnail (works for JPEG/HEIF/AVIF)
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageCoder.m
  SDWebImage/Core/SDImageIOAnimatedCoder.m
  SDWebImage/Core/SDImageIOCoder.m
  Tests/Tests/SDImageCoderTests.m
Labels: feature, heif

#2986 Feature pass the set operation key into context option from upstream. Fix the potential retain cycle if user use custom manager
  SDWebImage/Core/UIView+WebCache.m
  Tests/Tests/SDWebCacheCategoriesTests.m
Labels: feature

#2990 Add the convenient request/response modifier, which provide HTTP header directly
  SDWebImage/Core/SDWebImageDownloaderDecryptor.h
  SDWebImage/Core/SDWebImageDownloaderRequestModifier.h
  SDWebImage/Core/SDWebImageDownloaderRequestModifier.m
  SDWebImage/Core/SDWebImageDownloaderResponseModifier.h
  SDWebImage/Core/SDWebImageDownloaderResponseModifier.m
  Tests/Tests/SDWebImageDownloaderTests.m
Labels: feature request, swift

#2985 Added the convenient transition options for macOS user. Deprecate the old timingFunction, which can use System API to achieve
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Core/SDWebImageTransition.h
  SDWebImage/Core/SDWebImageTransition.m
  SDWebImage/Core/UIView+WebCache.m
  SDWebImage/Private/SDWebImageTransitionInternal.h
Labels: macOS

#2992 Add quary original chche for transformed image
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageDefine.m
  SDWebImage/Core/SDWebImageManager.m
Labels: discussion
