Repository SDWebImage/SDWebImage, pull requests merged in 2020-03, with the labels that each got.

#2954 Fix the rare case when call `SDWebImageDownloaderOperation.cancel`, the completion block may callback twice
  SDWebImage/Core/SDWebImageDownloaderOperation.m
Labels: bug

#2953 Add a better check to handle the cases when call `storeImage` without imageData
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCache.m
  Tests/Tests/SDImageCacheTests.m
  Tests/Tests/SDWebImageDownloaderTests.m
Labels: Behavior Changes

#2955 Feature add context option for cache, loader and coder, deprecated SDWebImageContextCustomManager
  SDWebImage/Core/SDImageCacheDefine.m
  SDWebImage/Core/SDImageLoader.m
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageDefine.m
  SDWebImage/Core/SDWebImageManager.m
  SDWebImage/Core/UIView+WebCache.m
Labels: Deprecation, feature

#2959 Fix the NotificationCenter does not remove the observer and little private header garden
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Private/SDAsyncBlockOperation.h
  SDWebImage/Private/SDDeviceHelper.h
  SDWebImage/Private/SDDisplayLink.h
  SDWebImage/Private/SDFileAttributeHelper.h
  SDWebImage/Private/SDFileAttributeHelper.m
  SDWebImage/Private/SDImageAssetManager.h
  SDWebImage/Private/SDImageCachesManagerOperation.h
  SDWebImage/Private/SDWeakProxy.h
Labels: fix, gardening

#2483 Keep the progressive decoding process only exist one per image download. Cancel the unused progressive decoding when full pixel data is available.
  SDWebImage/Core/SDWebImageDownloaderOperation.m
Labels: important

#2962 Update README.md
  README.md
Labels: documents
