Repository SDWebImage/SDWebImage, pull requests merged in 2021-02, with the labels that each got.

#3168 Fix link to v3.7.6 in README.md
  README.md
Labels: documents

#3167 Don't unnecessarily copy image data in the Download Operation
  SDWebImage/Core/SDWebImageDownloaderOperation.m
Labels: performance

#3177 Update UIView+WebCache.m
  SDWebImage/Core/UIView+WebCache.m
Labels: gardening
