Repository SDWebImage/SDWebImage, pull requests merged in 2021-04, with the labels that each got.

#3149 Don't encode/decode image when app will terminated
  SDWebImage/Core/SDImageCodersManager.m
  SDWebImage/Core/SDImageIOAnimatedCoder.m
  Tests/Tests/SDImageCoderTests.m
Labels: ImageIO, apple bug

#3205 Ensure the invalid URLSeesion will receive the cancel callback and does not trigger the any exception from framework
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageDownloaderOperation.m
Labels: crash

#3210 Change the willTerminate auto clean cache logic into sync version
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDImageCacheConfig.h
  SDWebImage/Core/SDImageCacheConfig.m
Labels: cache

#3219 Change the .originalStoreCaheType and .originalQueryCacheType into .disk, Now we will store the full image data into disk and re-query the full image data by default
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageManager.m
Labels: Behavior Changes

#3221 Fix the bug that when querying original cache miss, the download process will be skipped. This is not designed behavior.
  SDWebImage/Core/SDWebImageManager.m
Labels: bug, fix, transformer
