Repository SDWebImage/SDWebImage, pull requests merged in 2023-07, with the labels that each got.

#3561 Fix macOS bug that SDImageCoderDecodeScaleDownLimitBytes still use the AnimatedImageRep and beyond the byte limit
  SDWebImage/Core/SDImageCoder.h
  SDWebImage/Core/SDImageCoderHelper.h
  SDWebImage/Core/SDImageCoderHelper.m
  SDWebImage/Core/SDImageIOAnimatedCoder.m
Labels: fix, macOS

#3559 Refactory the logic to handle force decode logic to avoid CA copy frame buffer, introduce SDImageForceDecodePolicy detailed control
  Examples/SDWebImage Demo/DetailViewController.m
  SDWebImage/Core/SDImageCache.h
  SDWebImage/Core/SDImageCache.m
  SDWebImage/Core/SDImageCacheDefine.m
  SDWebImage/Core/SDImageCoderHelper.h
  SDWebImage/Core/SDImageCoderHelper.m
  SDWebImage/Core/SDImageGraphics.m
  SDWebImage/Core/SDImageLoader.m
  SDWebImage/Core/SDWebImageDefine.h
  SDWebImage/Core/SDWebImageDefine.m
  SDWebImage/Core/SDWebImageDownloader.h
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageDownloaderOperation.m
  SDWebImage/Core/UIImage+ForceDecode.h
  SDWebImage/Core/UIImage+ForceDecode.m
  SDWebImage/Core/UIImage+Transform.m
  SDWebImage/Private/SDDeviceHelper.m
  Tests/Tests/SDImageCoderTests.m
  Tests/Tests/SDUtilsTests.m
  Tests/Tests/SDWebImageManagerTests.m
Labels: performance, Behavior Changes

#3573 Expose the data and format when SDAnimatedImageRep created with APNG/GIF/WebP/HEICS
  SDWebImage/Core/SDAnimatedImage.h
  SDWebImage/Core/SDAnimatedImageRep.h
  SDWebImage/Core/SDAnimatedImageRep.m
  SDWebImage/Core/UIImage+MultiFormat.h
  SDWebImage/Core/UIImage+MultiFormat.m
  Tests/Tests/SDImageCoderTests.m
Labels: macOS

#3572 Fix redundant requests for the same url during decoding time
  SDWebImage/Core/SDWebImageDownloader.m
  SDWebImage/Core/SDWebImageDownloaderOperation.m
Labels: performance, bandwidth

#3576 Add better support for stateful view (UIButton) for image URL/progres s state management
  SDWebImage.xcodeproj/project.pbxproj
  SDWebImage/Core/NSButton+WebCache.m
  SDWebImage/Core/UIButton+WebCache.h
  SDWebImage/Core/UIButton+WebCache.m
  SDWebImage/Core/UIImageView+HighlightedWebCache.h
  SDWebImage/Core/UIImageView+HighlightedWebCache.m
  SDWebImage/Core/UIImageView+WebCache.h
  SDWebImage/Core/UIImageView+WebCache.m
  SDWebImage/Core/UIView+WebCache.h
  SDWebImage/Core/UIView+WebCache.m
  SDWebImage/Core/UIView+WebCacheState.h
  SDWebImage/Core/UIView+WebCacheState.m
  SDWebImage/Private/SDInternalMacros.h
  SDWebImage/include/SDWebImage/UIView+WebCacheState.h
  Tests/Tests/SDWebCacheCategoriesTests.m
  WebImage/SDWebImage.h
Labels: feature
